use t388;
show tables;
-- ORDER BY CLAUSE
select * from employee order by department;
select * from employee where gender ="male" order by fullname;

-- W G H O 
-- WHERE , GROUP BY-[HAVING] , ORDER BY 


select DEPARTMENT, COUNT(EMPLOYEEID) from employee GROUP BY DEPARTMENT; 
SELECT GENDER , COUNT(EMPLOYEEID) FROM EMPLOYEE GROUP BY GENder;
select DEPARTMENT , SUM(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT;
SELECT DEPARTMENT , avg(SALARY)  FROM EMPLOYEE GROUP BY DEPARTMENT;
SELECT DEPARTMENT , avg(SALARY) AS AVG_SALARY, SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEE GROUP BY DEPARTMENT;
SELECT AVG(SALARY) FROM EMPLOYEE;
SELECT DEPARTMENT , COUNT(*) FROM EMPLOYEE GROUP BY DEPARTMENT HAVING SUM(SALARY) >150000 ;
-- HAVING CLAUSE ( ALONG WITH GROUP BY CLAUSE) 
SELECT DEPARTMENT , AVG(AGE), COUNT(*) FROM EMPLOYEE GROUP BY DEPARTMENT ;
SELECT * FROM EMPLOYEE;


CREATE TABLE Projects ( ProjectId INT PRIMARY KEY AUTO_INCREMENT,
ProjectName VARCHAR(200) NOT NULL,
 EmployeeId INT,
StartDate DATETIME,
EndDate DATETIME );

INSERT INTO Projects VALUES(1,'Develop Ecommerse Website from
scratch', 1003, NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY)),
(2,'WordPress Website for our company',
1002, NOW(), DATE_ADD(NOW(), INTERVAL 45 DAY)),
(3,'Manage our Company Servers', 1007,
NOW(), DATE_ADD(NOW(), INTERVAL 45 DAY)),
(4,'Hosting account is not working', 1009,
NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY)),
(5,'MySQL database from my desktop
application', 1010, NOW(), DATE_ADD(NOW(), INTERVAL 15 DAY)),
(6,'Develop new WordPress plugin for my business
website', NULL, NOW(), DATE_ADD(NOW(), INTERVAL 10 DAY)),
(7,'Migrate web application and database to
new server', NULL, NOW(), DATE_ADD(NOW(), INTERVAL 5 DAY)),
(8,'Android Application development', 1004,
NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY)),
(9,'Hosting account is not working', 1001,
NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY)),
(10,'MySQL database from my desktop
application', 1008, NOW(), DATE_ADD(NOW(), INTERVAL 15 DAY)),
(11,'Develop new WordPress plugin for my
business website', NULL, NOW(), DATE_ADD(NOW(), INTERVAL 10 DAY));
 alter table projects ADD DURATION INT;
 
UPDATE PROJECTS SET DURATION =DATEDIFF(ENDDATE, STARTDATE);
SELECT DURATION ,COUNT(*) FROM PROJECTS GROUP BY DURATION;
SELECT DURATION,COUNT(*) FROM PROJECTS GROUP BY DURATION HAVING COUNT(*)>=2;
SELECT DURATION,COUNT(*) FROM PROJECTS GROUP BY DURATION HAVING COUNT(*)>=2 LIMIT 3;
SELECT DURATION,COUNT(*) FROM PROJECTS 
WHERE DURATION >=20 
GROUP BY DURATION 
HAVING COUNT(*)>=2
ORDER BY DURATION DESC;
select * from projects;
  
 
SELECT * FROM EMPLOYEE
ORDER BY EMPLOYEEID DESC LIMIT 5;
 
SELECT * FROM EMPLOYEE LIMIT 2,3;
SELECT * FROM EMPLOYEE LIMIT 3,5;
select distinct department from employee;
select distinct gender from employee;

SELECT * FROM EMPLOYEE;
select * from projects where employeeid is null;
 -- auto increment 
 desc projects;
 SELECT NOW();
UPDATE PROJECTS set employeeid = 1003 where  PROJECTID = 6;
UPDATE PROJECTS SET  EMPLOYEEID = 1007 WHERE PROJECTID = 7;

-- IN , BETWEEN AND LIKE

SELECT * FROM EMPLOYEE WHERE AGE BETWEEN 25 AND 27;
SELECT * FROM EMPLOYEE WHERE EMPLOYEEID BETWEEN 1003 AND 1007; -- between

SELECT * FROM EMPLOYEE WHERE EMPLOYEEID IN (1003, 1005, 1007);
SELECT * FROM EMPLOYEE WHERE EMPLOYEEID IN (1008); -- IN 

SELECT * FROM EMPLOYEE WHERE 
AGE IN (23, 28)
AND DEPARTMENT = "IT";

-- LIKE OPERATAOR
USE T388;
SELECT * FROM EMPLOYEE WHERE FULLNAME LIKE "M%";
SELECT * FROM EMPLOYEE WHERE FULLNAME LIKE "J%"; -- STARTING WORD OF FULLNAME IS J
SELECT * FROM EMPLOYEE WHERE FULLNAME LIKE "%Y"; -- ENDING WORD OF FULLNAME IS Y

SELECT * FROM EMPLOYEE WHERE FULLNAME LIKE "_A%"; -- SINGLE CHARACTER FROM START
SELECT * FROM EMPLOYEE WHERE FULLNAME LIKE "%_A" ; -- SINGLE CHARACTER FROM END
SELECT * FROM EMPLOYEE WHERE FULLNAME LIKE "__a%"; -- 

SELECT * FROM EMPLOYEE; 

SELECT * FROM SIMPLE;
SELECT * FROM SIMPLE WHERE FULLNAME LIKE "A%";
SELECT * FROM SIMPLE WHERE FULLNAME LIKE "_U%";
SELECT * FROM SIMPLE WHERE FULLNAME LIKE "%AN%"; 
SELECT * FROM SIMPLE WHERE FULLNAME LIKE "A%T";
SELECT * FROM SIMPLE WHERE FULLNAME NOT LIKE "A%T";

SELECT AVG(SALARY) FROM EMPLOYEE ;
SELECT SUM(SALARY) FROM EMPLOYEE ;
SELECT MAX(SALARY) FROM EMPLOYEE ;
SELECT MIN(SALARY) FROM EMPLOYEE ;
SELECT count(*), AVG(SALARY),SUM(SALARY) FROM EMPLOYEE;
SELECT COUNT(*) AS TOTAL_EMP , 
AVG(SALARY) AS AVERAGE ,
SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEE;

-- MATH FUNCTION
SELECT ABS(-35);
SELECT ABS(+35);
SELECT ABS(6*(-7));
SELECT ABS(DATEDIFF(STARTDATE , ENDDATE))
AS DURATION FROM PROJECTS;

SELECT MOD(12,7); -- FIRST DIVIDEND THEN DIVISOR THE ANSWER WILL BE REMINDER
SELECT MOD(12,3);

SELECT ceil(33.8); -- GIVES HIGHER NUMBER (CELING)
SELECT floor(33.8); -- GIVES LOWER NUMBER (FLOOR) (MOSTLY ASKED IN MOCK AND INTERVIEW)

SELECT truncate(123456.8765432,2); -- THE LAST NUMBER AFTER , SELECT THE VALUES AFTER DECIMAL
 SELECT truncate(123456.8765432,0); 
SELECT truncate(123456.8765432,-1); -- - REMOVE THE NUMBER BEFORE DECIMAL 

select exp( 2 );
select power(3,2);
SELECT SQRT(16); -- SQUARE ROOT 
SELECT SQRT(196);
SELECT SQRT(SALARY) FROM EMPLOYEE;

SELECT * FROM SIMPLE ;

SELECT CONCAT("GOOD" , " " ,"MORNING") AS REMARK;
SELECT *, CONCAT(FULLNAME , "-" , DEPARTMENT) AS CODE FROM EMPLOYEE;
SELECT *, CONCAT(FULLNAME ,"@ITVEDANT.COM ") AS CODE FROM EMPLOYEE;
SELECT * , LOWER(FULLNAME) AS NEWNAME , UPPER(FULLNAME) AS CAPITALNAME FROM EMPLOYEE;

ALTER TABLE EMPLOYEE ADD EMAIL VARCHAR (20);
ALTER TABLE EMPLOYEE MODIFY EMAIL VARCHAR (50);
UPDATE EMPLOYEE SET EMAIL = CONCAT(FULLNAME, "@GMAIL.COM");
SELECT REPLACE("HELLO EVERYONE , GOOD MORNING" , "MORNING","NIGHT") AS STATEMENT;
SELECT FULLNAME,REPLACE(FULLNAME,"Jones","PATIL") AS CHANGED FROM EMPLOYEE;
SELECT reverse(FULLNAME) FROM EMPLOYEE;
SELECT FULLNAME, LENGTH(FULLNAME) FROM EMPLOYEE;
SELECT SALARY, LENGTH(SALARY) FROM EMPLOYEE;
SELECT SUBSTRING("MAHARASHTRA",1,5); -- GIVE THE FIRST 5 POSITION OF LETTERS
-- SELECT FULLNAME, LENGTH(FULLNAME),
-- LTRIM(FULLNAME, LENGTH(LTRIM(FULLNAME)) AS LTRIM_LENGTH, 
-- RTRIM(FULLNAME) AS RTRIM_LENGTH , LEMGTH(RTRIM(FULLNAME)) AS RTRIM LENGTH,
-- TRIM(FULLNAME) AS BOTH_SIDES_TRIM, LENGTH(RTRIM(FULLNAME)) AS ALL_TRIM_LENGTH FROM TRIMER;
 
 -- SUB QUERIES
 SELECT AGE FROM EMPLOYEE WHERE EMPLOYEEID = (1002);
 SELECT AGE FROM EMPLOYEE WHERE FULLNAME = "Mary Smith";
 select * from employee where age = ( SELECT AGE FROM EMPLOYEE WHERE FULLNAME = "Mary Smith");
 
 select salary from employee where fullname =("John Doe");
 select * from employee where salary =( select salary from employee where fullname =("John Doe"));
 
  select * from employee where department=( select department from employee where fullname =("John Doe"));
  select max(salary) from employee;
  select max(salary) from employee where salary< (select max(salary) from employee);
select max(salary) from employee 
where salary< (select max(salary) from employee where salary< (select max(salary) from employee));
select* from employee;
 SELECT * FROM EMPLOYEE;

use T388;
select * from name ;
select * from salary ;
-- inner join
select  salary,name,salary     from 
name
join
salary
on salary = name;

select  name,name,salary 
from 
name
left join
salary
on salary = name;

-- outer join 
select * from name;
select * from salary;
select n.ID as NAME_ID, s.ID as SALARY_ID, name, salary
from name as n
left join 
salary as s
on  s.ID = n.ID 
union all
select n.ID as NAME_ID, s.ID as SALARY_ID, name, salary
from name as n
right join 
salary as s
on  s.ID = n.ID ;

 